### ISSUE TITLE
Add ORF9b to list of genes

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/Codon2Nucleotide#11]
It's possible that ORF9b is relevant, we use it within Nextstrain/Nextclade, but it's missing in Codon2Nucleotide.

On the other hand, I haven't seen ORF10 used much - is there much evidence for it being functional, should we include it in Nextstrain?

**Comment by theosanderson** [comment]
Codon2Nucleotide relies (apart from the special features for ORF1ab) on there being a 1:1 (i.e. non-overlapping) mapping from nuc to gene, which doesn't apply in this case - so it's a bit tricky. Easier would be to add it to Gensplore, which I can do.

**Comment by theosanderson** [comment]
This should be done here: https://github.com/theosanderson/gensplore/pull/18 (a bit iffy because it's not actually in the genbank annotation, but eh)
