### ISSUE TITLE
Bug with NSP12 mapping?

### ISSUE THREAD

**Issue by chaoran-chen** [theosanderson/Codon2Nucleotide#6]
Hi @theosanderson and @zach-hensel, I'm a bit confused by the NSP to ORF1a/b mapping. If I enter `ORF1ab:4402`, the tool returns `ORF1b:1` and `NSP12:10` but if I enter `NSP12:10`, I get `ORF1a:4402` which does not actually exist? Is it possible that the following line is wrong?

https://github.com/theosanderson/Codon2Nucleotide/blob/b3144c6f33ba2553e328ad498eed26ad4f43879a/src/App.js#L95

**Comment by chaoran-chen** [comment]
@corneliusroemer just explained to me the frameshift problem with NSP12... For CoV-Spectrum where we just also implemented the translation, I think that we will show a warning when people enter NSP12.

**Comment by corneliusroemer** [comment]
It sort of looks right here, orf1a is used by default, but when it's after the slippage, it's switched to orf1b
https://github.com/theosanderson/Codon2Nucleotide/blob/b3144c6f33ba2553e328ad498eed26ad4f43879a/src/App.js#L108-L111

The thing is that nuc 13468 is in both ORF1a and ORF1b, it's the last nuc of the last codon of ORF1a, and the first nuc of the first codon of ORF1b.

You can play with it here and will notice that there are only 2 nucs in the last codon of ORF1a.

Correct output would be that this nuc appears twice: in last codon of ORF1a and first of ORF1b
https://codon2nucleotide.theo.io/
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/25161793/174642568-0b262a5f-d15f-4bb4-baa6-8d1b28ec7cd4.png">

**Comment by theosanderson** [comment]
Thanks both! I think this is somewhat fixed by #7. Cornelius's point that there are multiple valid answers is true and not addressed, but the bigger point about much of nsp12 pointing to a codon that doesn't exist is I think addressed.
