### ISSUE TITLE
ENH: Extend codon2nucleotide to monkeypox

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/Codon2Nucleotide#8]
Talking to Vitor Borges, we realised that there is a need for a tool like codon2nucleotide for monkeypox - especially for translating between different reference coordinate systems.

I may try to figure this out myself if I have time but I thought I first raise this here as you may be interested in extending the great tool you already have - generalise it a bit.

Basically the question is: position 14611 in Rivers, what is it in MA001 etc

Sequencers may not all use Rivers as reference, so in their mappings the coordinates are different.

**Comment by theosanderson** [comment]
Thanks for raising -- while I am interested in generalising this to other organisms it would still be in a codon -> nucleotide way, and even that isn't imminent, so I'd encourage you to go for it
