### ISSUE TITLE
BUG: Website not indexed by Google

### ISSUE THREAD

**Issue by corneliusroemer** [theosanderson/Codon2Nucleotide#9]
I often struggle finding the website as it's not indexed by Google very well.

Maybe two things could help potential users (there may be more than you think) find it:
1. Add a bit of text describing what the website does
2. Give it a separate domain name - being a subdomain may not be 
3. Check Google SEO tools to see whether the page is properly indexed - the following screenshot makes me doubt that given random tweets show up before the website itself
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/25161793/188609265-02ed7893-03e9-4f43-9313-e5e31d9aa445.png">

Various cool domain names are still available (I hope mentioning them here doesn't make people buy them all up)

e.g. `c2n` `.` `bio`, or `cd2n` with various extensions

**Comment by corneliusroemer** [comment]
Funnily enough, DDG finds it perfectly
<img width="979" alt="image" src="https://user-images.githubusercontent.com/25161793/188609872-cad724f9-da8b-45ef-922d-5de17efdc763.png">

Probably should stop using google...

**Comment by theosanderson** [comment]
Expanded meta desc: https://github.com/theosanderson/Codon2Nucleotide/commit/6fb37b83b0a4ba3f67e932ce23c5586941ad2dfe - other points are not planned. I think a major determinant of Google rankings is number of incoming links, of which there are not that many.

**Comment by theosanderson** [comment]
For me the same query works with Google, but maybe that's because it knows I'm into theo.io..

**Comment by theosanderson** [comment]
(adding "web app" seems to be the issue, I guess because it prevents the URL from matching as well)
